### ISSUE TITLE
請問如何批量刪除已添加但尚未完成的任務?

### ISSUE THREAD

**Issue by Eugen1993** [707wk/ZERODownloadTool#1]
您好,
最近試用了一下, 除了下載比較慢和添加太多任務時程式會崩潰外, 體驗還蠻滿意的, 但想請問假設已添加了數百個未完成的任務, 除了一個一個手動刪除的方式, 有沒有什麼方法可以清空(取消)所有未完成任務, 因為我有重新下載原始程式檔案取代舊的程式檔案, 但已添加的未完成任務仍會持續出現, 所以看起來任務檔是記錄在我電腦上不確定的某個位置? 謝謝

**Comment by 707wk** [comment]
感谢反馈, 删除未完成任务的功能会在下次更新时添加

**Comment by AC-LGTM** [comment]
请问一下找不到卸载，这个程序怎么卸载呀，系统自带的显示不出来

**Comment by 707wk** [comment]
> 请问一下找不到卸载，这个程序怎么卸载呀，系统自带的显示不出来

免安装的, 不需要的话直接删除就行了

**Comment by AC-LGTM** [comment]
想问一下，能不能加一个暂停下载，有时候有事情，但是还没下完，然后我想问一下如果下的时候显示最后几卷未将对象引用到设置对象，这时候我搞个VLP是会自动下载还是说要删除重新去找然后下载
