### ISSUE TITLE
想问一下，能不能加一个暂停下载，有时候有事情，但是还没下完，然后我想问一下如果下的时候显示最后几卷未将对象引用到设置对象，这时候我搞个VLP是会自动下载还是说要删除重新去找然后下载

### ISSUE THREAD

**Issue by 707wk** [707wk/ZERODownloadTool#2]
想问一下，能不能加一个暂停下载，有时候有事情，但是还没下完，然后我想问一下如果下的时候显示最后几卷未将对象引用到设置对象，这时候我搞个VLP是会自动下载还是说要删除重新去找然后下载

_Originally posted by @AC-LGTM in https://github.com/707wk/ZERODownloadTool/issues/1#issuecomment-1407411783_

**Comment by 707wk** [comment]
直接退出, 程序会保存下载进度, 下次启动点全部开始按钮后会继续下载. VLP是什么?

**Comment by AC-LGTM** [comment]
经常会出现下到一半，然后就下载不了显示未将对象引
